app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class utilisateur(UserMixin, db.Model):
    """
    Create an user table
    """

    # Ensures table will be named in plural and not in singular
    # as is the name of the model
    __tablename__ = 'utilisateurs'

    id = db.Column(db.Integer, primary_key=True,unique=True)
    nom = db.Column(db.String(60), index=True)
    prenom = db.Column(db.String(60), index=True)
    email = db.Column(db.String(60), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    is_invite = db.Column(db.Boolean, default=False)
    is_admin = db.Column(db.Boolean, default=False)
    is_vendeur = db.Column(db.Boolean, default=False)
    username = db.Column(db.String(60), index=True, unique=True)

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<utilisateur: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return utilisateur.query.get(int(user_id))




 

app/__init__.py
# third-party imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
# local imports
from config import app_config

# db variable initialization
db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    
    Bootstrap(app)
    db.init_app(app)



    login_manager.init_app(app)
    login_manager.login_message = "Vous devez vous connecter pour acceder a cette page."
    login_manager.login_view = "auth_microservice.login"

    migrate = Migrate(app, db)

      

    from app import models
    

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .auth import auth_microservice as auth_microservice_blueprint
    app.register_blueprint(auth_microservice_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

  
    return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)
from . import views

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template
from flask_login import login_required

from .import home

@home.route('/')
def homepage():
     
     """
    Render the homepage template on the / route
    
     """
     return render_template('home/index.html',title="Welcome")

@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

app/templates/base.html
<!-- app/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>

    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>aranoz</title>
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/all.css') }}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/flaticon.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/themify-icons.css') }}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css') }}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slick.css') }}">
    <!-- style CSS -->
    
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                  <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                  <li><a href="{{ url_for('auth_microservice.logout') }}">Logout</a></li>
                  <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.username }}!</a></li>
                {% else %}
                  <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                  <li><a href="{{ url_for('auth_microservice.register') }}">Register</a></li>
                  <li><a href="{{ url_for('auth_microservice.login') }}">Login</a></li>
                {% endif %}
            </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                        <li class="footer-menu-divider">⋅</li>
                        {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth_microservice.logout') }}">Logout</a></li>
                        {% else %}
                          <li><a href="{{ url_for('auth_microservice.register') }}">Register</a></li>
                          <li class="footer-menu-divider">⋅</li>
                          <li><a href="{{ url_for('auth_microservice.login') }}">Login</a></li>
                        {% endif %}
                    </ul>
                    <p class="copyright text-muted small">Copyright © 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>